using System;
using System.Collections;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Xml.Linq;
using System.Data.SqlClient;
using System.Text;

namespace WebApplication1.AMS
{
    public partial class ForgetPasswordLink : System.Web.UI.Page
    {
        SqlCommand cmd;
        DataTable dt;
        SqlConnection con = new SqlConnection();
        SqlDataAdapter adp;

        protected void Page_Load(object sender, EventArgs e)
        {
            con = new SqlConnection();
            con.ConnectionString = ConfigurationManager.ConnectionStrings["infoConnectionString"].ToString();
            con.Open();
            if (con.State == ConnectionState.Closed)
            {
                con.Open();
            }

        }
        protected void btn_send_Click(object sender, EventArgs e)
        {
            if (con.State == ConnectionState.Closed)
            { con.Open(); }
            try
            {
                // here in SqlDataAdapter i am executing sql query if after the execution of this query there will be any data inside the datatable then
                // execute the else condition. otherwise it enter in the if condition and display message "Enter valid email address or uname".
                // in the below query i am checking uname and email address entered by the user with the values inside the database
                adp = new SqlDataAdapter("select FirstName,PersonalEmail from Registration where PersonalEmail=@PersonalEmail or FirstName=@FirstName", con);
                //here a i am passing parameter named email from the txt_email.Text's value
                adp.SelectCommand.Parameters.AddWithValue("@PersonalEmail", txt_email.Text);
                //here a i am passing parameter named uname from the txt_uname.Text's value
                adp.SelectCommand.Parameters.AddWithValue("@FirstName", txt_uname.Text);

                dt = new DataTable();
                adp.Fill(dt);
                if (dt.Rows.Count == 0)
                {
                    lbl_msg.Text = "Enter valid email address or username";
                    txt_email.Text = "";
                    txt_uname.Text = "";
                    return;
                }
                else
                {
                    // if the values entered by the user will be correct then this code will execute.
                    // below inside the code variable i am catching the autogenerated value which will different evertime.
                    string code;
                    code = Guid.NewGuid().ToString();
                    // and am updating the code column of the table with this value. i mean inside the code column i'll store the value
                    // that was inside the code variable
                    cmd = new SqlCommand("update Registration set code=@code where  PersonalEmail=@PersonalEmail or FirstName=@FirstName", con);
                    cmd.Parameters.AddWithValue("@code", code);
                    cmd.Parameters.AddWithValue("@PersonalEmail", txt_email.Text);
                    cmd.Parameters.AddWithValue("@FirstName", txt_uname.Text);
                    // here i am difinning a StringBuilder class named sbody
                    StringBuilder sbody = new StringBuilder();
                    // here i am sendind a image as logo with the path http://usingaspdotnet.blogspot.com
                    sbody.Append("<a href=http://usingaspdotnet.blogspot.com><img src=http://a1.twimg.com/profile_images/1427057726/asp_image.jpg/></a></br>");
                    // here i am sending a link to the user's mail address with the three values email,code,uname
                    // these three values i am sending  this link with the values using querystring method.
                    sbody.Append("<a href=http://localhost:51749/AMS/ResetPassword.aspx?PersonalEmail=" + txt_email.Text);
                    sbody.Append("&code=" + code + "&FirstName=" + txt_uname.Text + ">Click here to change your password</a>");
                    //in the below line i am sending mail with the link to the user.
                    //in this line i am passing four parameters 1st sender's mail address ,2nd receiever mail address, 3rd Subject,4th sbody.ToString() there will be complete link
                    // inside the sbody
                    System.Net.Mail.MailMessage mail = new System.Net.Mail.MailMessage("testusercpplus@gmail.com", dt.Rows[0]["PersonalEmail"].ToString(), "Reset Your Password", sbody.ToString());
                   // mail.CC.Add("any other email address if u want for cc");
                    //in the below  i am declaring the receiever email address and password
                    System.Net.NetworkCredential mailAuthenticaion = new System.Net.NetworkCredential("testusercpplus@gmail.com ", "ashna!123");
                    // in the below  i am declaring the smtp address of gmail and port number of the gmail
                    System.Net.Mail.SmtpClient mailclient = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587);
                    mailclient.EnableSsl = true;
                    mailclient.Credentials = mailAuthenticaion;
                    // here am setting the property IsBodyHtml true because i am using html tags inside the mail's code
                    mail.IsBodyHtml = true;
                    mailclient.Send(mail);
                    cmd.ExecuteNonQuery();
                    cmd.Dispose();
                    con.Close();
                    //lbl_msg.Text = "Link has been sent to your email address";
                    Response.Write("<script>alert('Link has been sent to your email address')</script>");
                    txt_email.Text = "";
                    txt_uname.Text = "";


                }
            }
            catch (Exception ex)
            {
                // if there will be any error created at the time of the sending mail then it goes inside the catch
                //and display the error in the label
                lbl_msg.Text = ex.Message;
            }
            finally
            {
                con.Close();
            }
        }
    }
}

//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.Web.UI;
//using System.Web.UI.WebControls;
//using System.Data;
//using System.Data.SqlClient;
//using System.Configuration;
//using System.Text;
//using System.Net.Mail;

//namespace WebApplication1.AMS
//{
//    public partial class ForgetPasswordLink : System.Web.UI.Page
//    {
//        SqlCommand cmd;
//        DataTable dt;
//        SqlConnection con = new SqlConnection();
//        SqlDataAdapter adp;

//        public static string to;

//        protected void Page_Load(object sender, EventArgs e)
//        {
//            con = new SqlConnection();
//            con.ConnectionString = ConfigurationManager.ConnectionStrings["infoConnectionstring"].ToString();
//            con.Open();
//            if (con.State == ConnectionState.Closed)
//            {
//                con.Open();
//            }

//        }
//        protected void btn_send_Click(object sender, EventArgs e)
//        {
//            if (con.State == ConnectionState.Closed)
//            { con.Open(); }
//            try
//            {
//                // here in SqlDataAdapter i am executing sql query if after the execution of this query there will be any data inside the datatable then
//                // execute the else condition. otherwise it enter in the if condition and display message "Enter valid email address or uname".
//                // in the below query i am checking uname and email address entered by the user with the values inside the database
//                adp = new SqlDataAdapter("select FirstName,PersonalEmail from Registration where PersonalEmail=@PersonalEmail or FirstName=@FirstName", con);
//                //here a i am passing parameter named email from the txt_email.Text's value
//                adp.SelectCommand.Parameters.AddWithValue("@PersonalEmail", txt_email.Text);
//                //here a i am passing parameter named uname from the txt_uname.Text's value
//                adp.SelectCommand.Parameters.AddWithValue("@FirstName", txt_uname.Text);

//                dt = new DataTable();
//                adp.Fill(dt);
//                if (dt.Rows.Count == 0)
//                {
//                    lbl_msg.Text = "Enter valid email address or Name";
//                    txt_email.Text = "";
//                    txt_uname.Text = "";
//                    return;
//                }
//                else
//                {
//                    // if the values entered by the user will be correct then this code will execute.
//                    // below inside the code variable i am catching the autogenerated value which will different evertime.
//                    string code;
//                    code = Guid.NewGuid().ToString();
//                    // and am updating the code column of the table with this value. i mean inside the code column i'll store the value
//                    // that was inside the code variable
//                    cmd = new SqlCommand("update Registration set code=@code where  PersonalEmail=@PersonalEmail or FirstName=@FirstName", con);
//                    cmd.Parameters.AddWithValue("@code", code);
//                    cmd.Parameters.AddWithValue("@PersonalEmail", txt_email.Text);
//                    cmd.Parameters.AddWithValue("@FirstName", txt_uname.Text);
//                    // here i am difinning a StringBuilder class named sbody
//                    StringBuilder sbody = new StringBuilder();
//                    // here i am sendind a image as logo with the path http://usingaspdotnet.blogspot.com
//                    //sbody.Append("<a href=http://usingaspdotnet.blogspot.com><img src=http://a1.twimg.com/profile_images/1427057726/asp_image.jpg/></a></br>");
//                    //// here i am sending a link to the user's mail address with the three values email,code,uname
//                    //// these three values i am sending  this link with the values using querystring method.
//                    //sbody.Append("<a href=http://localhost:51749/AMS/ForgetPassword2.aspx" + txt_email.Text);
//                    //sbody.Append("&code= four parameters 1st sender's mail address ,2nd receiever mail address, 3rd Subject,4th sbody.ToString() there will be complete link
//                    //// inside the sbody


//                    sbody.Append("Dear user" + ",<br/><br/>");
//                    sbody.Append("Please click on below link to reset your password");
//                    sbody.Append("<br/>");
//                    sbody.Append("<a href=http://localhost:51749/AMS/ResetPassword.aspx?PersonalEmail = " + txt_email.Text);
//                    sbody.Append("&code=" + code + "&FirstName=" + txt_uname.Text + ">Click here to change your password</a>"); 
//                    sbody.Append("<br/><br/>");
//                    sbody.Append("AMS system");

//                    System.Net.Mail.MailMessage mail = new System.Net.Mail.MailMessage("testusercpplus@gmail.com", dt.Rows[0]["personalemail"].ToString(), "reset your password", sbody.ToString());
//                    mail.From = new MailAddress("testusercpplus@gmail.com");
//                    mail.To.Add(new MailAddress(txt_email.Text).ToString());
//                    //mailmessage mail = new mailmessage("testusercpplus@gmail.com", txt_email.text.trim());
//                    //to = (txt_email.Text).ToString();
//                    //txt_email.Text = Session["PersonalEmail"].ToString();



//                    //  mail.CC.Add("any other email address if u want for cc");
//                    //in the below  i am declaring the receiever email address and password
//                    System.Net.NetworkCredential mailAuthenticaion = new System.Net.NetworkCredential("testusercpplus@gmail.com ", "ashna!123");
//                    // in the below  i am declaring the smtp address of gmail and port number of the gmail
//                    System.Net.Mail.SmtpClient mailclient = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587);
//                    mailclient.EnableSsl = true;
//                    mailclient.Credentials = mailAuthenticaion;
//                    // here am setting the property IsBodyHtml true because i am using html tags inside the mail's code
//                    mail.IsBodyHtml = true;
//                    mailclient.Send(mail);

//                    cmd.ExecuteNonQuery();
//                    cmd.Dispose();
//                    con.Close();
//                    lbl_msg.Text = "Link has been sent to your email address";
//                    txt_email.Text = "";
//                    txt_uname.Text = "";
//                   // Response.Redirect("ResetPassword.aspx");


//                }
//            }
//            catch (Exception ex)
//            {
//                // if there will be any error created at the time of the sending mail then it goes inside the catch
//                //and display the error in the label
//                lbl_msg.Text = ex.Message;
//            }
//            finally
//            {
//                con.Close();
//            }
//        }
//    }
//}
